### ISSUE TITLE
can't use Weather method. 

### ISSUE THREAD

**Issue by layth49** [swiftyspiffy/OpenWeatherMap-API-CSharp#25]
You can only use:

ValidRequest

Coordinates 

WeatherList (is it supposed to be this? It returns nothing)

Base 

Main

Visibility

Wind

Rain

Snow

Clouds

Sys

ID

Name

Cod

I looked into the package and it looks like everything needed is there for Weather but I can't use it.

**Comment by swiftyspiffy** [comment]
Sorry for delay. Yes, "Weather" is "WeatherList" (multiple weathers can exist concurrently). I just tested this:

```
var openWeatherAPI = new OpenWeatherAPI.OpenWeatherApiClient("...");
var query = openWeatherAPI.Query("anchorage");
Console.WriteLine(string.Format("The temperature in {0}, {1} is currently {2} °F", query.Name,query.Sys.Country, query.Main.Temperature.FahrenheitCurrent));
foreach(var weather in query.WeatherList)
    Console.WriteLine($"Id: {weather.ID}\nMain: {weather.Main}\nDescription: {weather.Description}\nIcon: {weather.Icon}");
```
and got:
```
The temperature in Anchorage, US is currently 30.092 °F
Id: 803
Main: Clouds
Description: broken clouds
Icon: 04d
```

And with query `mukachevo`:
```
The temperature in Mukachevo, UA is currently 68.882 °F
Id: 804
Main: Clouds
Description: overcast clouds
Icon: 04d
```

And with query `king cove`:
```
The temperature in King Cove, US is currently 17.708 °F
Id: 701
Main: Mist
Description: mist
Icon: 50n
Id: 601
Main: Snow
Description: snow
Icon: 13n
```

**Comment by swiftyspiffy** [comment]
This is 1.0.2 from nuget by the way. That is to say, I think things are working, its just the city you queried didnt have any weather data available from openweathermap. Closing (feel free to comment/reopen if needed).
