### ISSUE TITLE
System.NullReferenceException: Object Reference not set to an instance of an object

### ISSUE THREAD

**Issue by SixthTitan** [swiftyspiffy/OpenWeatherMap-API-CSharp#3]
System.NullReferenceException: Object Reference not set to an instance of an object at OpenWeatherAPI.Sys.cs line 21

Line 21:
if (sysData.SelectToken("type") != null)
                Type = int.Parse(sysData.SelectToken("type").ToString());

Notes:
Commenting lines 19-31 on Sys.cs and Line 61 in query.cs seems to correct the problem.
sys.cs /*
        public Sys(JToken sysData)
        {
            if (sysData.SelectToken("type") != null)
                Type = int.Parse(sysData.SelectToken("type").ToString());
            if (sysData.SelectToken("id") != null)
                ID = int.Parse(sysData.SelectToken("id").ToString());
            Message = double.Parse(sysData.SelectToken("message").ToString());
            Country = sysData.SelectToken("country").ToString();
            Sunrise = convertUnixToDateTime(double.Parse(sysData.SelectToken("sunrise").ToString()));
            Sunset = convertUnixToDateTime(double.Parse(sysData.SelectToken("sunset").ToString()));
        }
*/
query.cs //sys = new Sys(jsonData.SelectToken("sys"));

**Comment by EricSmith17** [comment]
same

**Comment by swiftyspiffy** [comment]
Sorry for the very long delay on this. Looking into this.

**Comment by swiftyspiffy** [comment]
This issue should be resolved now. Closing this, feel free to reopen if needed.
